repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        args: ["crudadmin", "--fix"]
      - id: ruff-format
        args: ["crudadmin"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy crudadmin/
        language: system
        types: [python]
        pass_filenames: false
        args: [--config-file=pyproject.toml]
